defaults:
  - writer: cometml
  - metrics: soundstream
  - datasets: librispeech
  - dataloader: soundstream
  - _self_


generator:
  _target_: src.model.generator.SoundStreamGenerator

discriminator:
  _target_: src.model.discriminator.SoundStreamDiscriminator

generator_optimizer:
  _target_: torch.optim.Adam
  lr: 2e-4

discriminator_optimizer:
  _target_: torch.optim.Adam
  lr: 2e-4

generator_loss_function:
  _target_: src.loss.soundstream_loss.SoundStreamGeneratorLoss

discriminator_loss_function:
  _target_: src.loss.soundstream_loss.SoundStreamDiscriminatorLoss

trainer:
  seed: 1
  device: auto
  log_step: 50
  n_epochs: 100
  epoch_len: 450
  device_tensors: ["audio"]
  resume_from: null
  override: false
  monitor: "off"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"

data:
  train_root: "data/LibriSpeech/LibriSpeech/train-clean-100"
  test_root: "data/LibriSpeech/LibriSpeech/test-clean"

audio:
  sample_rate: 16000
  crop_seconds: 0.5
  channels: 1
